apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: test
  labels:
    app: client
spec:
  nodeName: ovn-worker
  containers:
    - name: client
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        ["sleep INF"]
